### ISSUE TITLE
APP input causes error

### ISSUE THREAD

**Issue by mjsduncan** [MOZI-AI/annotation-service#13]
APP is in the production data set, it has appeared as a biogrid annotation for another gene, but as an input gene it produces this error:

Python-Scheme Wrapper: Failed to execute '(annotate-genes (list \"APP\" ) \"fGJmJaa\" (delay (list (gene-info (list \"APP\" )) ( gene-go-annotation (list \"APP\" )  \"biological_process cellular_component molecular_function\" 0)( gene-pathway-annotation (list \"APP\" )  \"reactome smpdb\"  \"True\"  \"True\" )( biogrid-interaction-annotation (list \"APP\" )  \"Proteins\" ))))'\nBacktrace:\n          14 (apply-smob/1 #<catch-closure 7f13f9da78a0>)\n          13 (apply-smob/1 #<catch-closure 7f13f9da77a0>)\nIn ice-9/boot-9.scm:\n   2312:4 12 (save-module-excursion _)\nIn ice-9/eval-string.scm:\n     38:6 11 (read-and-eval #<input: string 7f13abcb37e0> #:lang _)\nIn ice-9/boot-9.scm:\n    152:2 10 (with-fluid* _ _ _)\n    152:2  9 (with-fluid* _ _ _)\n    152:2  8 (with-fluid* _ _ _)\n    152:2  7 (with-fluid* _ _ _)\n    152:2  6 (with-fluid* _ _ _)\n    152:2  5 (with-fluid* _ _ _)\nIn ice-9/eval.scm:\n    155:9  4 (_ _)\n    619:8  3 (_ #(#(#(#(#(#(#(#<directory (guile-?>) ?) ?) ?) ?) ?) ?))\nIn ice-9/ports.scm:\n    469:4  2 (with-input-from-port _ _)\nIn ice-9/boot-9.scm:\n   751:25  1 (dispatch-exception 0 nyacc-error (\"~A:~A: parse fai?\" ?))\nIn unknown file:\n           0 (apply-smob/1 #<catch-closure 7f13f9da7760> nyacc-error ?)\n\nERROR: In procedure apply-smob/1:\nIn procedure ~A:~A: parse failed at state ~A, on input ~S: Error while printing exception.\nABORT: nyacc-error\n (/root/atomspace/opencog/cython/opencog/PyScheme.cc:63)

**Comment by mjsduncan** [comment]
getting an error with the new pull (this is from BRCA1 input but i'm putting it here since the newest commit was addressing this error)

`annotation-service |` 2019-07-09 12:03:15,542 - annotation-service - INFO - Scheme Func: (list (gene-info (list "BRCA1" )) ( gene-pathway-annotation (list "BRCA1" )  "reactome"  "False"  "False" )( biogrid-interaction-annotation (list "BRCA1" )  "Proteins" ))
`annotation-service |` 2019-07-09 12:03:15,542 - annotation-service - INFO - doing annotation (annotate-genes (list "BRCA1" ) "JjXWdba" (delay (list (gene-info (list "BRCA1" )) ( gene-pathway-annotation (list "BRCA1" )  "reactome"  "False"  "False" )( biogrid-interaction-annotation (list "BRCA1" )  "Proteins" ))))
`annotation-service |` 2019-07-09 12:03:17,040 - annotation-service - ERROR - Error: <traceback object at 0x7ff9519f3948>
...
`annotation-service |` time="2019-07-09T12:03:17-04:00" level=info msg="finished streaming call" error="rpc error: code = InvalidArgument desc = Error occurred in while trying to perform request: Python-Scheme Wrapper: Failed to execute '(annotate-genes (list \"BRCA1\" ) \"JjXWdba\" (delay (list (gene-info (list \"BRCA1\" )) ( gene-pathway-annotation (list \"BRCA1\" )  \"reactome\"  \"False\"  \"False\" )( biogrid-interaction-annotation (list \"BRCA1\" )  \"Proteins\" ))))'\nBacktrace:\nIn ice-9/boot-9.scm:\n    152:2 19 (with-fluid* _ _ _)\nIn ice-9/eval.scm:\n   293:34 18 (_ #(#(#<directory (guile-user) 7ff95c717140> #<pro…> …)))\n    155:9 17 (_ _)\nIn unknown file:\n          16 (force #<promise #<procedure 7ff9684133c0 at ice-9/eval…>)\nIn ice-9/eval.scm:\n    163:9 15 (_ #(#(#<directory (guile-user) 7ff95c717140>)))\n    619:8 14 (_ #(#(#(#<directory (guile-user) 7ff95c717140>) # …) …))\nIn srfi/srfi-1.scm:\n    640:9 13 (for-each #<procedure 7ff9684059a0 at ice-9/eval.scm:3…> …)\n    640:9 12 (for-each #<procedure 7ff968405420 at ice-9/eval.scm:3…> …)\nIn ice-9/eval.scm:\n   293:34 11 (_ #(#(#<directory (guile-user) 7ff95c717140> \"BR…\" …) …))\n    619:8 10 (_ #(#(#(#<directory (guile-user) 7ff95c717140>) # …) …))\n   626:19  9 (_ #(#(#(#<directory (guile-user) 7ff95c717140>) # …) …))\n    155:9  8 (_ _)\nIn srfi/srfi-1.scm:\n   592:17  7 (map1 (# # # # # # # # # # # # # # # # #))\nIn ice-9/eval.scm:\n    619:8  6 (_ #(#(#(#<directory (guile-user) 7ff95c717140> …) #) …))\n   626:19  5 (_ #(#(#(#<directory (guile-user) 7ff95c717140> …) #) …))\n    159:9  4 (_ _)\n    155:9  3 (_ _)\nIn unknown file:\n           2 (opencog-extension cog-execute! (#))\nIn ice-9/boot-9.scm:\n   751:25  1 (dispatch-exception 0 C++-EXCEPTION (\"cog-execute!\" \"…\"))\nIn unknown file:\n           0 (apply-smob/1 #<catch-closure 7ff9684005a0> # \"cog-exe…\" …)\n\nERROR: In procedure apply-smob/1:\nIn procedure cog-execute!: Backtrace:\nIn ice-9/eval.scm:\n    155:9 19 (_ _)\nIn unknown file:\n          18 (force #<promise #<procedure 7ff9684133c0 at ice-9/eval…>)\nIn ice-9/eval.scm:\n    163:9 17 (_ #(#(#<directory (guile-user) 7ff95c717140>)))\n    619:8 16 (_ #(#(#(#<directory (guile-user) 7ff95c717140>) # …) …))\nIn srfi/srfi-1.scm:\n" grpc.code=InvalidArgument grpc.method=Annotate grpc.service=Annotate grpc.start_time="2019-07-09T12:02:52-04:00" grpc.time_ms=24142 span.kind=server system=grpc

**Comment by mjsduncan** [comment]
same error generated with `IGF1` which worked in previous pull.

**Comment by mjsduncan** [comment]
same error with `APP`
$ git submodule status
 2b9114fec6f3db0f2da928635a23bb8aaa2a93d9 annotation-result-ui (remotes/origin/HEAD)
 fac8c0d5436185e29cdbacb9d4f8e7f4c193fd3a react (remotes/origin/HEAD)
 f119939995069f7ebe7dc89c6ed17539fb3fb32e scheme (remotes/origin/HEAD)
 2f29a5bf2c5e755c1bb3076cd321c6590460f927 utils/scm2csv (remotes/origin/HEAD)

**Comment by Habush** [comment]
@mjsduncan There was a malformed data for the APP GO annotation. It has been fixed now. Can you update the [GO.scm](https://mozi.ai/datasets/GO.scm) and try again?

**Comment by mjsduncan** [comment]
error from APP after updating the datasets:
annotation-service | 2019-08-15 20:53:27,538 - annotation-service - INFO - when executing atoms:5873731
annotation-service |
annotation-service | 2019-08-15 20:53:27,539 - annotation-service - INFO - Scheme Func: (list (gene-info (list "APP" )) ( gene-go-annotation (list "APP" )  "biological_process cellular_component molecular_function" )( gene-pathway-annotation (list "APP" )  "smpdb reactome"  "True"  "True" )( biogrid-interaction-annotation (list "APP" )  "Proteins" ))
annotation-service | 2019-08-15 20:53:27,539 - annotation-service - INFO - doing annotation (annotate-genes (list "APP" ) "Oq9-Fba" (delay (list (gene-info (list "APP" )) ( gene-go-annotation (list "APP" )  "biological_process cellular_component molecular_function" )( gene-pathway-annotation (list "APP" )  "smpdb reactome"  "True"  "True" )( biogrid-interaction-annotation (list "APP" )  "Proteins" ))))
annotation-service | 2019-08-15 20:57:53,416 - annotation-service - ERROR - Error: Python-Scheme Wrapper: Failed to execute '(annotate-genes (list "APP" ) "Oq9-Fba" (delay (list (gene-info (list "APP" )) ( gene-go-annotation (list "APP" )  "biological_process cellular_component molecular_function" )( gene-pathway-annotation (list "APP" )  "smpdb reactome"  "True"  "True" )( biogrid-interaction-annotation (list "APP" )  "Proteins" ))))'
annotation-service | Backtrace:
annotation-service |            8 (apply-smob/1 #<catch-closure 7fd8f3d6d860>)
annotation-service |            7 (apply-smob/1 #<catch-closure 7fd8f3d6d760>)
annotation-service | In ice-9/boot-9.scm:
annotation-service |    2312:4  6 (save-module-excursion _)
annotation-service | In ice-9/eval-string.scm:
annotation-service |      38:6  5 (read-and-eval #<input: string 7fd8f355a0e0> #:lang _)
annotation-service | In annotation/main.scm:
annotation-service |     71:24  4 (annotate-genes _ )
annotation-service | In annotation/parser.scm:
annotation-service |     247:8  3 (atomese-parser _ _)
annotation-service | In ice-9/ports.scm:
annotation-service |     469:4  2 (with-input-from-port _ _)
annotation-service | In ice-9/boot-9.scm:
annotation-service |    751:25  1 (dispatch-exception 0 nyacc-error ("~A:~A: parse fai…" …))
annotation-service | In unknown file:
annotation-service |            0 (apply-smob/1 #<catch-closure 7fd8f3d6d720> nyacc-error …)
annotation-service |
annotation-service | ERROR: In procedure apply-smob/1:
annotation-service | In procedure ~A:~A: parse failed at state ~A, on input ~S: Error while printing exception.
annotation-service | ABORT: nyacc-error
annotation-service |  (/root/atomspace/opencog/cython/opencog/PyScheme.cc:63)
annotation-service | time="2019-08-15T20:57:53+08:00" level=error msg="finished streaming call" error="rpc error: code = Internal desc = an internal error occured. please try again" grpc.code=Internal grpc.method=Annotate grpc.service=Annotate grpc.start_time="2019-08-15T20:53:27+08:00" grpc.time_ms=265899 span.kind=server system=grpc
m duncan 21:51

**Comment by mjsduncan** [comment]
after reloading input page and re-entering APP w/o smpdb a couple time i got these errors:
annotation-service | 2019-08-15 21:18:16,827 - annotation-service - INFO - Current PID: 88
annotation-service | 2019-08-15 21:18:16,956 - annotation-service - INFO - checking genes : (list "APP" )
annotation-service | 2019-08-15 21:18:16,960 - annotation-service - INFO - (list "APP" )
annotation-service | 2019-08-15 21:18:16,969 - annotation-service - WARNING - result : 0
annotation-service | 2019-08-15 21:18:16,974 - annotation-service - WARNING - 0
annotation-service |
annotation-service | 2019-08-15 21:19:47,187 - annotation-service - ERROR - Error: <traceback object at 0x7fd9151a5cc8>
annotation-service | time="2019-08-15T21:19:47+08:00" level=info msg="finished streaming call" error="rpc error: code = InvalidArgument desc = Error occurred in while trying to perform request: mongo:27017: [Errno -3] Temporary failure in name resolution" grpc.code=InvalidArgument grpc.method=Annotate grpc.service=Annotate grpc.start_time="2019-08-15T21:18:16+08:00" grpc.time_ms=90367 span.kind=server system=grpc
ui          | 172.18.0.1 - - [15/Aug/2019:13:44:53 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" "-"
ui          | 172.18.0.1 - - [15/Aug/2019:13:44:53 +0000] "GET /bundle.js HTTP/1.1" 304 0 "http://localhost:3003/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" "-"
ui          | 172.18.0.1 - - [15/Aug/2019:13:44:54 +0000] "GET /src/assets/mozi_globe.e45aa4be670209bde81189ebbdcc6aea.png HTTP/1.1" 200 189899 "http://localhost:3003/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" "-"
ui          | 172.18.0.1 - - [15/Aug/2019:13:44:54 +0000] "GET /src/assets/bg.0b9017a22b64daada94f56c0ff2765d9.svg HTTP/1.1" 304 0 "http://localhost:3003/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" "-"
annotation-service | 2019-08-15 21:45:20,862 - annotation-service - INFO - Current PID: 88
annotation-service | 2019-08-15 21:45:20,863 - annotation-service - INFO - checking genes : (list "APP" )
annotation-service | 2019-08-15 21:45:20,863 - annotation-service - INFO - (list "APP" )
annotation-service | 2019-08-15 21:45:20,864 - annotation-service - WARNING - result : 0
annotation-service | 2019-08-15 21:45:20,864 - annotation-service - WARNING - 0
annotation-service |
annotation-service | 2019-08-15 21:46:51,053 - annotation-service - ERROR - Error: <traceback object at 0x7fd9151b7248>
annotation-service | time="2019-08-15T21:46:51+08:00" level=info msg="finished streaming call" error="rpc error: code = InvalidArgument desc = Error occurred in while trying to perform request: mongo:27017: [Errno -3] Temporary failure in name resolution" grpc.code=InvalidArgument grpc.method=Annotate grpc.service=Annotate grpc.start_time="2019-08-15T21:45:20+08:00" grpc.time_ms=90193 span.kind=server system=grpc

**Comment by mjsduncan** [comment]
after resetting the service, it generated the scm file for APP (it exists in results folder) but i never got a results link page and the shell log generated a bunch of messages like this:
mongo_1_f9567473e027 | 2019-08-15T17:00:39.411+0000 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 71, after asserts: 185, after backgroundFlushing: 362, after connections: 733, after dur: 848, after extra_info: 1095, after freeMonitoring: 1535, after globalLock: 1946, after locks: 2274, after logicalSessionRecordCache: 2404, after network: 2714, after opLatencies: 2892, after opReadConcernCounters: 3087, after opcounters: 3311, after opcountersRepl: 3447, after repl: 3554, after security: 3566, after storageEngine: 3576, after tcmalloc: 3598, after transactions: 3598, after transportSecurity: 3598, after wiredTiger: 3700, at end: 3763 }
....
us was very slow: { after basic: 61, after asserts: 417, after backgroundFlushing: 417, after connections: 461, after dur: 474, after extra_info: 474, after freeMonitoring: 637, after globalLock: 1141, after locks: 2101, after logicalSessionRecordCache: 3058, after network: 5221, after opLatencies: 6142, after opReadConcernCounters: 6644, after opcounters: 8089, after opcountersRepl: 8257, after repl: 8257, after security: 8257, after storageEngine: 8553, after tcmalloc: 11309, after transactions: 12412, after transportSecurity: 13325, after wiredTiger: 56954, at end: 56964 }
mongo_1_f9567473e027 | 2019-08-15T17:06:06.962+0000 I COMMAND  [PeriodicTaskRunner] task: DBConnectionPool-cleaner took: 1622ms
mongo_1_f9567473e027 | 2019-08-15T17:06:07.321+0000 I COMMAND  [LogicalSessionCacheRefresh] command config.system.sessions command: listIndexes { listIndexes: "system.sessions", cursor: {}, $db: "config" } numYields:0 reslen:324 locks:{ Global: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } storage:{} protocol:op_msg 237ms
mongo_1_f9567473e027 | 2019-08-15T17:06:08.280+0000 I NETWORK  [conn2] end connection 172.18.0.5:40550 (2 connections now open)
mongo_1_f9567473e027 | 2019-08-15T17:06:08.289+0000 I NETWORK  [conn3] end connection 172.18.0.5:40552 (1 connection now open)
annotation-service | time="2019-08-16T01:06:08+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, TRANSIENT_FAILURE" system=system
annotation-service | time="2019-08-16T01:06:08+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, CONNECTING" system=system
annotation-service | time="2019-08-16T01:06:08+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, READY" system=system

**Comment by mjsduncan** [comment]
after resseting and trying again with vpn off, scheme file generated but python process filled up ram and maxed out swap drive so i had to shut it down before getting a results screen.
```
annotation-service | 2019-08-16 13:19:11,384 - annotation-service - INFO - doing annotation (annotate-genes (list "APP" ) "4Fk3fda" (delay (list (gene-info (list "APP" )) ( gene-go-annotation (list "APP" )  "biological_process cellular_component molecular_function" )( gene-pathway-annotation (list "APP" )  "reactome"  "True"  "True" )( biogrid-interaction-annotation (list "APP" )  "Proteins" ))))
mongo_1_f9567473e027 | 2019-08-16T05:20:44.773+0000 I COMMAND  [PeriodicTaskRunner] task: DBConnectionPool-cleaner took: 122ms
annotation-service | 2019-08-16 13:27:30,597 - annotation-service - INFO - saving result in file : /root/result/scheme/4Fk3fda.scm
annotation-service | 2019-08-16 13:27:30,604 - annotation-service - INFO - Filename: /root/result/scheme/4Fk3fda.scm
annotation-service | E0816 15:19:30.981285890     128 chttp2_transport.cc:2801]   ipv4:127.0.0.1:50762: Keepalive watchdog fired. Closing transport.
annotation-service | time="2019-08-16T15:19:31+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42018a220, TRANSIENT_FAILURE" system=system
annotation-service | time="2019-08-16T15:19:31+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42018a220, CONNECTING" system=system
annotation-service | time="2019-08-16T15:19:31+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42018a220, READY" system=system
annotation-service | time="2019-08-16T15:19:31+08:00" level=warning msg="finished streaming call" error="rpc error: code = Unavailable desc = keepalive watchdog timeout" grpc.code=Unavailable grpc.method=Annotate grpc.service=Annotate grpc.start_time="2019-08-16T13:19:10+08:00" grpc.time_ms=7.220059e+06 span.kind=server system=grpc
annotation-service | 2019-08-16 15:19:31,593 - annotation-service - INFO - Current PID: 88
annotation-service | 2019-08-16 15:19:31,649 - annotation-service - INFO - checking genes : (list "APP" )
annotation-service | 2019-08-16 15:19:31,649 - annotation-service - INFO - (list "APP" )
annotation-service | 2019-08-16 15:19:31,753 - annotation-service - WARNING - result : 0
annotation-service | 2019-08-16 15:19:31,753 - annotation-service - WARNING - 0
annotation-service | 
mongo_1_f9567473e027 | 2019-08-16T07:19:32.142+0000 I NETWORK  [listener] connection accepted from 172.18.0.5:42964 #4 (4 connections now open)
mongo_1_f9567473e027 | 2019-08-16T07:19:32.207+0000 I NETWORK  [conn4] received client metadata from 172.18.0.5:42964 conn4: { driver: { name: "PyMongo", version: "3.9.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-25-generic" }, platform: "CPython 3.5.2.final.0" }
mongo_1_f9567473e027 | 2019-08-16T07:19:32.269+0000 I NETWORK  [listener] connection accepted from 172.18.0.5:42966 #5 (5 connections now open)
mongo_1_f9567473e027 | 2019-08-16T07:19:32.271+0000 I NETWORK  [conn5] received client metadata from 172.18.0.5:42966 conn5: { driver: { name: "PyMongo", version: "3.9.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-25-generic" }, platform: "CPython 3.5.2.final.0" }
annotation-service | 2019-08-16 15:19:32,459 - annotation-service - INFO - when executing atoms:5872616
annotation-service | 
annotation-service | 2019-08-16 15:19:32,461 - annotation-service - INFO - Scheme Func: (list (gene-info (list "APP" )) ( gene-go-annotation (list "APP" )  "biological_process cellular_component molecular_function" )( gene-pathway-annotation (list "APP" )  "reactome"  "True"  "True" )( biogrid-interaction-annotation (list "APP" )  "Proteins" ))
annotation-service | 2019-08-16 15:19:32,462 - annotation-service - INFO - doing annotation (annotate-genes (list "APP" ) "hh__1da" (delay (list (gene-info (list "APP" )) ( gene-go-annotation (list "APP" )  "biological_process cellular_component molecular_function" )( gene-pathway-annotation (list "APP" )  "reactome"  "True"  "True" )( biogrid-interaction-annotation (list "APP" )  "Proteins" ))))
annotation-service | 2019-08-16 15:32:26,847 - annotation-service - INFO - saving result in file : /root/result/scheme/hh__1da.scm
annotation-service | 2019-08-16 15:32:26,985 - annotation-service - INFO - Filename: /root/result/scheme/hh__1da.scm
mongo_1_f9567473e027 | 2019-08-16T07:53:43.275+0000 I WRITE    [conn5] update snet_annotation.sessions command: { q: { id: BinData(3, F5FFF1C7F15B4634BA15AE31A71EDF63) }, u: { $set: { annotations: [ { filters: [ { value: "biological_process cellular_component molecular_function", filter: "namespace" }, { value: "", filter: "parents" } ], function_name: "gene-go-annotation" }, { filters: [ { value: "reactome", filter: "namespace" }, { value: "True", filter: "include_prot" }, { value: "True", filter: "include_small_molecule" } ], function_name: "gene-pathway-annotation" }, { filters: [ { value: "Proteins", filter: "interaction" } ], function_name: "biogrid-interaction-annotation" } ], end_time: 0, status: -1, id: BinData(3, F5FFF1C7F15B4634BA15AE31A71EDF63), message: "", expired: false, mnemonic: "hh__1da", result: "{"nodes" : [{"data" : {"id" : "KEAP1","name" : "Kelch-like ECH-associated protein 1","definition" : "https://www.ncbi.nlm.nih.gov/gene/9817","location...", _id: ObjectId('5d5659030e353fca8a60ba4e'), csv_file: null, start_time: 1565939972.352785, genes: [ { gene_name: "APP" } ], result_file: "/root/result/scheme/hh__1da.scm" } }, multi: false, upsert: false } planSummary: COLLSCAN keysExamined:0 docsExamined:7 nMatched:1 nModified:1 numYields:2 locks:{ Global: { acquireCount: { r: 3, w: 3 } }, Database: { acquireCount: { w: 3 } }, Collection: { acquireCount: { w: 3 } } } storage:{ data: { bytesWritten: 15864233, timeWritingMicros: 2336 } } 924ms
mongo_1_f9567473e027 | 2019-08-16T07:53:43.283+0000 I COMMAND  [conn5] command snet_annotation.$cmd command: update { update: "sessions", ordered: true, lsid: { id: UUID("e1928f1e-406d-4b42-aa1b-c7e78db36090") }, $db: "snet_annotation", $readPreference: { mode: "primary" } } numYields:0 reslen:60 locks:{ Global: { acquireCount: { r: 5, w: 3 } }, Database: { acquireCount: { w: 3 } }, Collection: { acquireCount: { w: 3 } } } storage:{} protocol:op_msg 1009ms
annotation-service | 2019-08-16 15:53:43,341 - annotation-service - ERROR - Error: 
mongo_1_f9567473e027 | 2019-08-16T07:55:02.808+0000 I WRITE    [conn5] update snet_annotation.sessions command: { q: { id: BinData(3, F5FFF1C7F15B4634BA15AE31A71EDF63) }, u: { $set: { annotations: [ { filters: [ { value: "biological_process cellular_component molecular_function", filter: "namespace" }, { value: "", filter: "parents" } ], function_name: "gene-go-annotation" }, { filters: [ { value: "reactome", filter: "namespace" }, { value: "True", filter: "include_prot" }, { value: "True", filter: "include_small_molecule" } ], function_name: "gene-pathway-annotation" }, { filters: [ { value: "Proteins", filter: "interaction" } ], function_name: "biogrid-interaction-annotation" } ], end_time: 1565942097.392762, status: -1, id: BinData(3, F5FFF1C7F15B4634BA15AE31A71EDF63), message: "Error: ", expired: false, mnemonic: "hh__1da", result: "{"nodes" : [{"data" : {"id" : "KEAP1","name" : "Kelch-like ECH-associated protein 1","definition" : "https://www.ncbi.nlm.nih.gov/gene/9817","location...", _id: ObjectId('5d5659030e353fca8a60ba4e'), csv_file: null, start_time: 1565939972.352785, genes: [ { gene_name: "APP" } ], result_file: "/root/result/scheme/hh__1da.scm" } }, multi: false, upsert: false } planSummary: COLLSCAN keysExamined:0 docsExamined:7 nMatched:1 nModified:1 numYields:1 locks:{ Global: { acquireCount: { r: 2, w: 2 } }, Database: { acquireCount: { w: 2 } }, Collection: { acquireCount: { w: 2 } } } storage:{ data: { bytesWritten: 15680273, timeWritingMicros: 48519 } } 4144ms
mongo_1_f9567473e027 | 2019-08-16T07:55:02.810+0000 I COMMAND  [conn5] command snet_annotation.$cmd command: update { update: "sessions", ordered: true, lsid: { id: UUID("e1928f1e-406d-4b42-aa1b-c7e78db36090") }, $db: "snet_annotation", $readPreference: { mode: "primary" } } numYields:0 reslen:60 locks:{ Global: { acquireCount: { r: 4, w: 2 } }, Database: { acquireCount: { w: 2 } }, Collection: { acquireCount: { w: 2 } } } storage:{} protocol:op_msg 5314ms
mongo_1_f9567473e027 | 2019-08-16T07:55:02.840+0000 I NETWORK  [conn5] end connection 172.18.0.5:42966 (4 connections now open)
mongo_1_f9567473e027 | 2019-08-16T07:55:02.840+0000 I NETWORK  [conn4] end connection 172.18.0.5:42964 (3 connections now open)
annotation-service | time="2019-08-16T15:55:03+08:00" level=error msg="finished streaming call" error="rpc error: code = Internal desc = an internal error occured. please try again" grpc.code=Internal grpc.method=Annotate grpc.service=Annotate grpc.start_time="2019-08-16T15:19:31+08:00" grpc.time_ms=2.131595e+06 span.kind=server system=grpc
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by mjsduncan** [comment]
malformed atomese fixed
