### ISSUE TITLE
Providing suggestions on genes that are not found in the knowledge base

### ISSUE THREAD

**Issue by Habush** [MOZI-AI/annotation-service#30]
We should provide a suggestion of similarly named gene symbols for users in case they can't find a symbol in our atomspace. E.g if the user requests gene symbol `POLA` which doesn't exist in our atomspace, then we should return `POLA1` and `POLA2` , which exist in out knowledge base, as suggestions.

**Comment by mjsduncan** [comment]
this has been done but it doesn't work very well.  a list of alternatives shows up in an info box in the input screen but it disappears quickly and doesn't make clear which suggestions are for which unknown symbol.  ideally, unknown sybols should turn red in the list under the input box, and hovering over them should produce the list of alternatives, one of which could be clicked to replace the unknown symbol.

**Comment by mjsduncan** [comment]
works well now, not sure which commit fixed it.  thanks!
