### ISSUE TITLE
project is not described

### ISSUE THREAD

**Issue by linas** [MOZI-AI/annotation-service#35]
At the top of https://github.com/MOZI-AI/annotation-service it says "No description, website, or topics provided." -- a single sentence description should be provided, and a website, and topics, too.

**Comment by mjsduncan** [comment]
here's a description but it appears i don't seem to have editing privileges for the description:

"the gene annotation service maps human gene symbols to their biological context as represented in an opencog knowledge hypergraph.  see README for details."

**Comment by linas** [comment]
I don't either; I'm not part of MOZI-AI system group, and there are no publicly-identified members:  https://github.com/orgs/MOZI-AI/people so we don't know who to contact.  So who is the MOZI-AI sysadmin/owner?

Also, the `annotation-scheme` is missing  description and tags, and if you look at the projects here: https://github.com/MOZI-AI about 2/3rds of them are missing descriptions of what they are...

**Comment by tanksha** [comment]
@mjsduncan I have added the above description to the annotation service.

**Comment by linas** [comment]
Hi @tanksha I think you can cut the part that says "see the README" because the README is already on the same page.  But also -- can you add tags, at least  a tag for "genetics", and  "visualization" or "visualizer" or "viewer", or whatever tags are popular.

**Comment by linas** [comment]
But also: after reading the README, it seems like the project is misnamed. It should be called "genetic-data-viewer" or maybe "HGNC-viewer" or "HGNC-visualizer" -- the current name "annotation-service" is nearly meaningless -- it could be annotating poetry -- you can't tell from the name -- and also its not a "service" in any normal sense of the word "service" -- it's a visualization and graphing tool.

**Comment by tanksha** [comment]
@linas sure, the biology team can have something better name than just annotation-service, we will discuss it on our weakly meeting tomorrow and edit. Thanks.

**Comment by linas** [comment]
I also asked Mike by private email -- is there a way of disentangling this from docker? Two reasons for this

1) Docker needlessly/pointlessly adds extra complexity/complication that makes everything harder to run, harder to debug, harder to work with.

2) Other containers, e.g. LXC, seem to be vastly superior to docker. Docker is kind of backwards and upside-down and not very well designed.  LXC blows the doors off of docker for ease-of-use, at least, at the level that I work...

**Comment by linas** [comment]
Here's a fun video about ease-of-use: totally off-topic, but its Christmas and its a fun video -- https://youtube.com/watch?v=pW-SOdj4Kkk

**Comment by mjsduncan** [comment]
we're stuck with docker for now, but you can run hypergraph subsetting code in guile from the [scheme module repository:](https://github.com/MOZI-AI/annotation-scheme)

**Comment by Habush** [comment]
Hi @linas. You can setup the project locally without the need for docker as long as your system has the python and scheme library dependencies. We use docker for deployment and it makes the process of setting up the project easy for newbies. I will look into LXC.

**Comment by linas** [comment]
Not sure how docker makes anything easier for anyone except cloud deployment people.  But if you  really want a docker-like thing without the pain-in-the-neckery of docker, use LXD or LXE, not LXC.  If you want ease-of-use on your personal computer, then LXC is better.  It all depends on which part of the "easy to use" profile you want to optimize.
