### ISSUE TITLE
Compression of datasets for download.

### ISSUE THREAD

**Issue by linas** [MOZI-AI/annotation-service#37]
The main README suggests  `wget -r --no-parent https://mozi.ai/datasets/` which downloads almost one gigabyte of datasets (999 MBytes on my system) But these are text scheme files -- if instead these were placed in a tar.gz file -- they would occupy 45 MBytes, and a tar.bz2 file, they'd occupy 26 MYbtes -- so about 40 times smaller, for a 40-times faster download.

**Comment by mjsduncan** [comment]
part of the issue is that the files change a lot with development and source data updates.  we do need a better system for sure, maybe a shell script that lives where ever the user wants to store the data that could be run periodically to check the repo and download and decompress new file versions.

**Comment by linas** [comment]
well, you don't actually need it to be periodic ... someone -- some human being, or some script, is publishing files at the `https://mozi.ai/datasets/` website. If it's a human publishing the website, just remember to `tar -jcf datasets.tar.bz2 datasets` and if its a script publishing the website -- just modify the script and add that line. 

Analogously for the user --- if the user is reading the README and following what it says .. just add a step to the README. If the user has a shell-script they'll need to modify it.  Sure, networks have gotten fast, but still -- The amount of time saved waiting for gigabyte-sized files to download is worth the compression.

**Comment by mjsduncan** [comment]
what about setting up rsync access to the data directory, then one could automatically pull compressed versions of the updated files

**Comment by linas** [comment]
I don't know what your use-case is. All I know is the README tells you to "do this", and, without any warning, you get a download bigger than a pirated movie. 

re: copying files: I don't know how often you update stuff there, who needs to get the contents, how important it is to always use the latest. If there's a handful of you and you do it weekly, then wget by hand is low-complexity. If you update nightly for dozens of users, then rsync cron jobs that run at night is a good idea.

I was exploring a distributed-atomspace solution kind-of-like filesharing (bittorrent-style) but there are design issues I have not yet resolved, so that's still futuristic. (The hope was you just get the atomspace name, connect to the network, and the needed parts of the atomspace that you're using are downloaded on demand. Easy to imagine, hard to get just right).

**Comment by vsbogd** [comment]
After compressing databases procedure in README.md doesn't work. After step 1 (https://github.com/MOZI-AI/annotation-service/blob/master/README.md#local-setup--development) dbs downloaded are compressed and annotation service tries to load them as is.

**Comment by vsbogd** [comment]
Am I right that all databases should be uncompressed before starting service?

**Comment by mjsduncan** [comment]
yes, directory with files needs to be uncompressed for access by service.
thanks, @tanksha !

**Comment by mjsduncan** [comment]
@Habush can you update the README.md so folks will set up the local installation correctly?

**Comment by Habush** [comment]
@mjsduncan I have updated the README in the latest commit.

**Comment by mjsduncan** [comment]
thanks, @Habush !
