### ISSUE TITLE
GO csv table should not return empty namespace columns if namespace not requested

### ISSUE THREAD

**Issue by mjsduncan** [MOZI-AI/annotation-service#8]
if only one or two namespaces is requested, the non-requested ones should not be listed as empty columns to avoid confusion with the case where a namespace is requested and there are no terms in that namespace linked to the input genes.

**Comment by tanksha** [comment]
This issue has been fixed 
Repo: https://github.com/MOZI-AI/scheme2csv
Commit number: 08d8e5cde97a5f5df19720d59015b3e267c607af
